k-kit-san/fleamarket_sample_79e

app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20200728021626_devise_create_users.rb, db/schema.rb, test/fixtures/users.yml, test/models/user_test.rb
新規登録・ログイン機能のマークアップのため
devise等をinstall
=> user devise

README.md
下記変更点をREADME.mdに反映
・profilesテーブルのカラムをusersテーブルに一部移動、修正(ER図は布田さんより既に修正済み)
・カラム名やカラムの型で間違っていた箇所を修正
　references型の時、カラム名は“item_id”ではなく“item”とする(“_id”は自動付与されるため)
・itemsテーブルの変更
　statusカラム削除 →購入済み商品かどうかの判断はbuyer_idの入力有無を確認することで区別出来そうなため
　shipping_methodカラム削除 →trolloを確認したところ、配送方法の登録は今回必要なかったため
　clothes_sizeカラム削除 →trolloを確認したところ、サイズ登録もなくても良かったため
・brandsテーブルの削除
　ブランドはitemsテーブルに下記の通りに登録した方が良さそうなため
　カラム名：brand　カラムの型：string
実装する内容と整合性をとるため修正
[ER_20200802.pdf](https://github.com/k-kit-san/fleamarket_sample_79e/files/5011760/ER_20200802.pdf)
=> データベース設計の変更

app/models/category.rb, app/models/condition.rb, app/models/item.rb, app/models/item_image.rb, app/models/postage.rb, app/models/prepare.rb, app/uploaders/item_image_uploader.rb, db/migrate/20200803030238_create_categories.rb, db/migrate/20200803030942_create_items.rb, db/migrate/20200803072151_create_item_images.rb, db/schema.rb, test/fixtures/categories.yml, test/fixtures/item_images.yml, test/fixtures/items.yml, test/models/category_test.rb, test/models/item_image_test.rb, test/models/item_test.rb
商品出品機能を実装する前に下記を準備した
・categoryモデルおよびテーブルの作成
・itemモデルおよびテーブルの作成
・item_imageモデルおよびテーブルの作成
・active hash追加（condition, postage, prepare)
・carrierwaveでを使用し、item_imageモデルで画像をアップロードできるよう準備
・アソシエーション、バリデーションの記述
**※まだuserモデルとitemモデルのアソシエーションは組んでいないので注意**
商品出品機能実装する前に、一旦共有化した方が全体的に作業が進みやすくなるため
=> 商品出品機能実装の下準備

README.md, app/assets/stylesheets/modules/_display.scss, app/views/dispray/index.html.haml
データベース設計、商品出品ページを修正した
（データベースはユーザー評価テーブルを削除）
早めに共有した方が作業しやすくなるため
=> データベース設計と商品出品ページの修正

spec/factories/delivery_address.rb, spec/factories/user.rb, spec/models/delivery_address_spec.rb, spec/rails_helper.rb
delivery_addressモデルのバリデーションテスト
不正な入力やエラーを防ぐ為
=> delivery_address_test

app/assets/stylesheets/modules/_log.scss, app/assets/stylesheets/users.scss, app/controllers/users_controller.rb, app/helpers/users_helper.rb, app/views/logs/index.html.haml, app/views/users/show.html.haml, config/routes.rb, test/controllers/users_controller_test.rb
user controllerの作成
user showのviewの作成
マイページからのログアウトのlink作成
ユーザーのshow(マイページ)は必須となるため
購入機能に必要なクレジットカード機能もマイページを使用するため。
=> user_show作成

Gemfile, app/models/user.rb, spec/factories/users.rb, spec/models/user_spec.rb, spec/rails_helper.rb
factory_botを用いてuserテーブルに登録する情報を設定し、userモデルのテストを行う
Userモデル記述のバリデーションなどの制約で、不正な入力やエラーを防ぐため
=> Userモデル関係のテスト

.gitignore, app/models/item.rb, spec/factories/item_images.rb, spec/factories/items.rb, spec/models/item_image_spec.rb, spec/models/item_spec.rb
RSpecとfactory_botを利用し、
商品出品機能で使用するitemモデルとitem_imageモデルのテストを行った
商品出品時の不正な入力やエラーを防ぐバリデーションが正常に動くか確認するため
=> itemモデルとitem_imageモデルのテスト

app/assets/javascripts/application.js, app/assets/javascripts/category.js, app/assets/javascripts/item.js, app/assets/stylesheets/modules/_items_new.scss, app/views/items/new.html.haml, app/views/layouts/application.html.haml
商品出品時における画像投稿フォームのjavascriptの修正(item.js)
画像の投稿数の上限は5枚としているが、
修正前のjavascriptの場合、複数枚アップロードした状態から連続で削除→再度アップロードした際に
4枚以下でしか登録できないことがあったため
=> 商品出品機能の画像投稿部分の修正

app/assets/stylesheets/_header.scss, app/assets/stylesheets/application.scss, app/views/layouts/_header.html.haml, app/views/layouts/application.html.haml
未実装だったトップページのヘッダー部分のビューを作成
（リンクや条件により表示を変えるなどの条件分岐は後ほど実装）
本アプリケーションにおいて検索時、新規登録やログイン時に使う部分であるため
=> ヘッダー部分のビューを追加

app/assets/stylesheets/_footer.scss, app/views/layouts/_footer.html.haml
未実装だったトップページのフッダー部分のビューを作成
本アプリケーションにおいて必須表示項目であるため
=> フッダー部分のビューを追加

app/controllers/users_controller.rb, app/views/users/show.html.haml
- マイページにて出品数を表示(累計の出品数)
- 商品出品ページへのlinkを追加
累計の出品数を確認できる
出品ページへのアクセスの簡素化
=> ユーザー出品数の表示

app/assets/stylesheets/modules/_registration.scss, app/views/devise/registrations/create_address.html.haml
- ビューの調整
- クレジットカード or トップページの選択ボタンを実装
クレジットカードの登録かトップページかをユーザーが選択できるようになる。
=> ユーザー登録完了画面の編集

app/assets/stylesheets/application.scss, app/views/items/new.html.haml, app/views/layouts/application.html.haml
商品出品ページ内のリンク先に誤りがあった箇所を修正
全ページにフッダーが表示されるよう設定
本アプリケーションを使いやすくするため
=> 商品出品ページの微調整と全ページにフッダーを配置

app/controllers/items_controller.rb, app/views/layouts/_header.html.haml
商品投稿者のみ商品情報を編集できるように修正
現状だと、ログインしていれば誰でも商品情報を書き換えられるため
=> 商品編集機能の利用権限を設定

db/migrate/20200730081552_create_delivery_addresses.rb, db/schema.rb
delivry_addressのマイグレーションファイルを変更
post_codeをintegerからstringへ
byte数でエラーとなっている
=> ユーザー本番環境エラー

app/controllers/users_controller.rb
ログインユーザーのIDと異なるIDでマイページに入れないように設定
ログインユーザーのID以外でマイページに入れないようにするため
=> user関連のアクセスを制限

app/controllers/items_controller.rb, app/views/items/show.html.haml
ニックネームとブランドをブラウザに表示させる
ニックネームとブランドがブラウザに表示されていなかったため
=> 商品詳細の未表示の項目を修正

app/assets/stylesheets/modules/_detail.scss, app/views/items/index.html.haml, app/views/items/show.html.haml
編集ボタンと、削除ボタン、購入ボタンを追加し、リンクを設定
商品の編集と削除、そして購入の三つの機能をブラウザのリンクから使えるようにするため
=> 商品詳細画面にボタンを追加

README.md
profilesテーブルの記述箇所を削除
本アプリケーションにおいてprofilesテーブルは使用していないため
=> README.mdのDB設計記述の変更
